### PR TITLE
removed null returned Connection

### PR DESCRIPTION
**Pull request by devender-yadav**
For incorrect url, it's throwing

    java.sql.SQLException: No suitable driver found for jdbc:blkchn:ethereum://localhost:8545
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.impetus.blkchn.eth.Query.main(Query.java:33)

With these changes:

    java.sql.SQLException: Couldn't connect with ethereum
	at com.impetus.eth.jdbc.EthConnection.verifyConnection(EthConnection.java:416)
	at com.impetus.eth.jdbc.EthConnection.<init>(EthConnection.java:109)
	at com.impetus.eth.jdbc.EthDriver.connect(EthDriver.java:65)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.impetus.blkchn.eth.Query.main(Query.java:33)

### CODE REVIEW

**Comment by devender-yadav** [comment]
@ashishkshukla `SQLException` is thrown by ` EthConnection(String url, Properties props)` and it simply propagated to its parent method as `connect(String url, Properties info)` is also throwing `SQLException`.

**Comment by ashishkshukla** [comment]
Yes. To standardized the process, we return BlkchnException  to the end user. 
Instead of returning null , we can put exception SQLException message in BlkchnException and return.

**Comment by ajay-shriwastava** [comment]
Psuedo code for Ashish's suggestion
method123 throws SQLException....
.....
catch(Exception ex){
//log the exception at error level
//throw ex
}

**Comment by ashishkshukla** [comment]
@devender-yadav .Closing as we have to handle this in a different way .

**Pull request closed without merging**
